using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using NetTopologySuite.Geometries;
using NetTopologySuite.Operation.Polygonize;
using NetTopologySuite.Operation.Union;

namespace DwgToPngPoC;

/// <summary>
/// Builds fill polygons from CAD outline linework that is not already one closed SVG element.
/// NTS unary union is intentionally used here because it fully nodes line crossings and T-junctions
/// before polygonizing. That is the part the previous endpoint-only graph could not handle.
/// </summary>
internal static class ClosedRegionReconstructor
{
    private static readonly Regex NumberOrCommandRegex = new(
        @"[MmLlHhVvZz]|[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    public static int AddFills(
        XElement root,
        string fillColor,
        double pixelScale,
        double sourceWidth,
        double sourceHeight)
    {
        if (!double.IsFinite(pixelScale) || pixelScale <= 0)
            return 0;

        foreach (var old in root.Descendants()
                     .Where(e => e.Name.LocalName == "g" &&
                                 string.Equals((string?)e.Attribute("class"), "app-generated-region-fills", StringComparison.Ordinal))
                     .ToArray())
        {
            old.Remove();
        }

        var span = Math.Max(Math.Abs(sourceWidth), Math.Abs(sourceHeight));
        if (!double.IsFinite(span) || span <= 0)
            span = 1;

        // Only remove numerical noise. The previous 0.5-pixel tolerance became tens of
        // drawing units on a very large drawing and could connect unrelated endpoints.
        // Relative rounding keeps true CAD junctions together without bridging visible gaps.
        var snapTolerance = Math.Max(1e-9, span * 1e-9);
        var precisionScale = Math.Clamp(1.0 / snapTolerance, 1.0, 1e9);

        var rawSegments = ExtractSegments(root, snapTolerance);
        if (rawSegments.Count < 3)
            return 0;

        var precisionModel = new PrecisionModel(precisionScale);
        var factory = new GeometryFactory(precisionModel);
        var lines = new List<Geometry>(rawSegments.Count);

        foreach (var segment in rawSegments)
        {
            var a = Snap(segment.A, precisionModel);
            var b = Snap(segment.B, precisionModel);
            if (a.Equals2D(b))
                continue;

            lines.Add(factory.CreateLineString(new[] { a, b }));
        }

        if (lines.Count < 3)
            return 0;

        // UnaryUnion fully nodes linework: every segment crossing and T-junction becomes
        // an endpoint in the result, and duplicate/coincident line portions are dissolved.
        Geometry nodedLinework;
        try
        {
            nodedLinework = UnaryUnionOp.Union(lines, factory);
        }
        catch
        {
            // A topology failure in optional fill reconstruction must not prevent conversion.
            return 0;
        }

        var polygonizer = new Polygonizer(false);
        polygonizer.Add(nodedLinework);

        // Ignore regions smaller than ~4 output pixels. This also suppresses most tiny
        // accidental loops generated by annotation fragments.
        var minimumArea = 4.0 / (pixelScale * pixelScale);
        var polygons = polygonizer.GetPolygons()
            .OfType<Polygon>()
            .Where(p => !p.IsEmpty && p.Area > minimumArea)
            .ToArray();

        if (polygons.Length == 0)
            return 0;

        var ns = root.Name.Namespace;
        var group = new XElement(ns + "g",
            new XAttribute("class", "app-generated-region-fills"),
            new XAttribute("fill", fillColor),
            new XAttribute("stroke", "none"),
            new XAttribute("fill-rule", "evenodd"));

        foreach (var polygon in polygons)
        {
            var d = BuildSvgPathData(polygon);
            if (d.Length == 0)
                continue;

            group.Add(new XElement(ns + "path", new XAttribute("d", d)));
        }

        if (!group.HasElements)
            return 0;

        // Keep generated fills behind the original CAD strokes/text.
        var firstDrawable = root.Elements().FirstOrDefault(e => e.Name.LocalName != "defs");
        if (firstDrawable is null)
            root.Add(group);
        else
            firstDrawable.AddBeforeSelf(group);

        return group.Elements().Count();
    }

    private static Coordinate Snap(PointD point, PrecisionModel precisionModel)
    {
        var coordinate = new Coordinate(point.X, point.Y);
        precisionModel.MakePrecise(coordinate);
        return coordinate;
    }

    private static string BuildSvgPathData(Polygon polygon)
    {
        var sb = new StringBuilder();
        AppendRing(sb, polygon.ExteriorRing);
        for (var i = 0; i < polygon.NumInteriorRings; i++)
            AppendRing(sb, polygon.GetInteriorRingN(i));
        return sb.ToString();
    }

    private static void AppendRing(StringBuilder sb, LineString ring)
    {
        var coordinates = ring.Coordinates;
        if (coordinates.Length < 4)
            return;

        if (sb.Length > 0)
            sb.Append(' ');

        sb.Append('M')
          .Append(Format(coordinates[0].X)).Append(' ')
          .Append(Format(coordinates[0].Y));

        for (var i = 1; i < coordinates.Length - 1; i++)
        {
            sb.Append('L')
              .Append(Format(coordinates[i].X)).Append(' ')
              .Append(Format(coordinates[i].Y));
        }

        sb.Append('Z');
    }

    private static string Format(double value) => value.ToString("0.########", CultureInfo.InvariantCulture);

    private static List<RawSegment> ExtractSegments(XElement root, double tolerance)
    {
        var result = new List<RawSegment>();

        foreach (var element in root.Descendants())
        {
            if (!IsVisibleStroke(element) || HasTransform(element))
                continue;

            switch (element.Name.LocalName)
            {
                case "line":
                    if (TryGetDouble(element, "x1", out var x1) &&
                        TryGetDouble(element, "y1", out var y1) &&
                        TryGetDouble(element, "x2", out var x2) &&
                        TryGetDouble(element, "y2", out var y2))
                    {
                        AddSegment(result, new PointD(x1, y1), new PointD(x2, y2), tolerance);
                    }
                    break;

                case "polyline":
                {
                    var points = ParsePoints((string?)element.Attribute("points"));
                    if (points.Count < 2)
                        break;

                    // Already-closed elements are handled by the direct fill pass.
                    if (points.Count >= 3 && AreClose(points[0], points[^1], tolerance))
                        break;

                    for (var i = 1; i < points.Count; i++)
                        AddSegment(result, points[i - 1], points[i], tolerance);
                    break;
                }

                case "path":
                {
                    var d = ((string?)element.Attribute("d"))?.Trim();
                    if (string.IsNullOrEmpty(d) || d.IndexOfAny(['Z', 'z']) >= 0)
                        break;

                    if (TryParseOpenLinearPath(d, out var pathSegments))
                    {
                        foreach (var segment in pathSegments)
                            AddSegment(result, segment.A, segment.B, tolerance);
                    }
                    break;
                }
            }
        }

        return result;
    }

    private static void AddSegment(List<RawSegment> segments, PointD a, PointD b, double tolerance)
    {
        if (!double.IsFinite(a.X) || !double.IsFinite(a.Y) ||
            !double.IsFinite(b.X) || !double.IsFinite(b.Y))
            return;

        var dx = b.X - a.X;
        var dy = b.Y - a.Y;
        if (dx * dx + dy * dy <= tolerance * tolerance)
            return;

        segments.Add(new RawSegment(a, b));
    }

    private static List<PointD> ParsePoints(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return [];

        var numbers = value
            .Split(new[] { ' ', ',', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(v => double.TryParse(v, NumberStyles.Float, CultureInfo.InvariantCulture, out var number)
                ? number
                : double.NaN)
            .ToArray();

        if (numbers.Length < 4 || numbers.Length % 2 != 0 || numbers.Any(double.IsNaN))
            return [];

        var points = new List<PointD>(numbers.Length / 2);
        for (var i = 0; i < numbers.Length; i += 2)
            points.Add(new PointD(numbers[i], numbers[i + 1]));
        return points;
    }

    private static bool TryParseOpenLinearPath(string data, out List<RawSegment> segments)
    {
        segments = [];

        // Closed curves are handled by the direct fill pass. Open curved paths are not
        // polygonized yet; straight CAD boundaries are by far the common case for rooms,
        // panels and table/grid cells, and NTS handles their intersections correctly.
        if (Regex.IsMatch(data, "[AaCcQqSsTt]", RegexOptions.CultureInvariant))
            return false;

        var tokens = NumberOrCommandRegex.Matches(data).Select(m => m.Value).ToArray();
        if (tokens.Length == 0)
            return false;

        var i = 0;
        char command = '\0';
        var current = new PointD(0, 0);
        var haveCurrent = false;

        while (i < tokens.Length)
        {
            if (IsCommand(tokens[i]))
            {
                command = tokens[i][0];
                i++;
                if (command is 'Z' or 'z')
                    return false;
            }

            if (command == '\0')
                return false;

            switch (command)
            {
                case 'M':
                case 'm':
                {
                    if (!TryReadPair(tokens, ref i, out var x, out var y))
                        return false;
                    current = command == 'm' && haveCurrent
                        ? new PointD(current.X + x, current.Y + y)
                        : new PointD(x, y);
                    haveCurrent = true;
                    command = command == 'm' ? 'l' : 'L';
                    break;
                }

                case 'L':
                case 'l':
                {
                    if (!haveCurrent || !TryReadPair(tokens, ref i, out var x, out var y))
                        return false;
                    var next = command == 'l'
                        ? new PointD(current.X + x, current.Y + y)
                        : new PointD(x, y);
                    segments.Add(new RawSegment(current, next));
                    current = next;
                    break;
                }

                case 'H':
                case 'h':
                {
                    if (!haveCurrent || !TryReadNumber(tokens, ref i, out var x))
                        return false;
                    var next = new PointD(command == 'h' ? current.X + x : x, current.Y);
                    segments.Add(new RawSegment(current, next));
                    current = next;
                    break;
                }

                case 'V':
                case 'v':
                {
                    if (!haveCurrent || !TryReadNumber(tokens, ref i, out var y))
                        return false;
                    var next = new PointD(current.X, command == 'v' ? current.Y + y : y);
                    segments.Add(new RawSegment(current, next));
                    current = next;
                    break;
                }

                default:
                    return false;
            }
        }

        return segments.Count > 0;
    }

    private static bool TryReadPair(string[] tokens, ref int index, out double x, out double y)
    {
        x = y = 0;
        return TryReadNumber(tokens, ref index, out x) && TryReadNumber(tokens, ref index, out y);
    }

    private static bool TryReadNumber(string[] tokens, ref int index, out double value)
    {
        value = 0;
        if (index >= tokens.Length || IsCommand(tokens[index]))
            return false;

        if (!double.TryParse(tokens[index], NumberStyles.Float, CultureInfo.InvariantCulture, out value))
            return false;
        index++;
        return true;
    }

    private static bool IsCommand(string token) => token.Length == 1 && char.IsLetter(token[0]);

    private static bool TryGetDouble(XElement element, string attribute, out double value)
    {
        return double.TryParse((string?)element.Attribute(attribute), NumberStyles.Float,
            CultureInfo.InvariantCulture, out value);
    }

    private static bool HasTransform(XElement element)
    {
        for (var current = element; current is not null; current = current.Parent)
        {
            if (!string.IsNullOrWhiteSpace((string?)current.Attribute("transform")))
                return true;
        }
        return false;
    }

    private static bool IsVisibleStroke(XElement element)
    {
        for (var current = element; current is not null; current = current.Parent)
        {
            var display = (string?)current.Attribute("display");
            if (string.Equals(display, "none", StringComparison.OrdinalIgnoreCase))
                return false;

            var stroke = (string?)current.Attribute("stroke");
            if (string.Equals(stroke, "none", StringComparison.OrdinalIgnoreCase))
                return false;
            if (!string.IsNullOrWhiteSpace(stroke))
                return true;
        }
        return false;
    }

    private static bool AreClose(PointD a, PointD b, double tolerance)
    {
        return Math.Abs(a.X - b.X) <= tolerance && Math.Abs(a.Y - b.Y) <= tolerance;
    }

    private readonly record struct PointD(double X, double Y);
    private readonly record struct RawSegment(PointD A, PointD B);
}
